name: Build and Release Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Create plugin zip
        run: npm run plugin-zip

      - name: Upload zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./prolific-blocks.zip
